[package]
name = "buf_read_splitter"
version = "3.0.0"
edition = "2021"
description = "Buffer reader with the capacity to split(stop) on a giving [u8] separator"
repository = "https://github.com/flogbl/buf_read_splitter"
license = "MIT"
exclude = [".gitignore"]
[dependencies]
