[package]
name = "buf_read_splitter"
version = "0.1.3"
edition = "2021"
description = "BufReadSplitter is a buffer split reader. It's like read_until but the separator can be more than one byte, also this separator is not returned (the buffer stop just before it)"
repository = "https://github.com/flogbl/buf_read_splitter"
license = "MIT"
license-file = "LICENSE"
exclude = [".gitignore"]
[dependencies]
buf_read_splitter_new = { package = "buf_read_splitter", version = "0.2" }
