[package]
name = "buf_read_splitter"
version = "0.4.2"
edition = "2021"
description = "A stream buffer reader with ability to split the stream until a defined pattern is reached (usually an array of [u8])"
repository = "https://github.com/flogbl/buf_read_splitter"
license = "MIT"
exclude = [".gitignore"]

[features]
default = []
#default = ["log"]
log = ["dep:log", "dep:format_hex", "dep:env_logger"]

[dependencies]
env_logger = { version = "0.7", optional = true }
format_hex = { version = "0.1", optional = true }
log = { version = "0.4", optional = true }
thiserror = "2"

[dev-dependencies]
sysinfo = "0.39"

[[bench]]
name = "main"
harness = false

# To use flamegraph
# Command example : cargo flamegraph --test count_on_huge_buffer
#[profile.release]
#debug = true
#strip = false

# for speed
[profile.release]
opt-level = 3
lto = "fat"
