[package]
name = "buf_read_splitter"
version = "0.2.1"
edition = "2021"
description = "BufReadSplitter can read a buffer giving an array as separator, stopping before each one encounter. The separator can be updated on the fly."
repository = "https://github.com/flogbl/buf_read_splitter"
license = "MIT"
license-file = "LICENSE"
exclude = [".gitignore"]
[dependencies]
